name = "mengxi-upload-worker"
main = "src/index.js"
compatibility_date = "2024-04-01"

# Bind the R2 Bucket
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "xixi-image-bed"
preview_bucket_name = "xixi-image-bed"
